script: src/evo/evo_2phase_trainer.py
arch: lenet
dataset: mnist
num_fe: 2500000
batch_size: 256
criterion: ce
adapter: global_uniform_binning_directly
optimizer: de
de_selection: best
de_mut_rate: 0.5
de_cr_rate: 0.7
de_jitter: true
de_num_diffs: 1
de_mut_prob: 0.9
seed: 42
alpha: 1.0
phase1_pop_init: uniform
phase1_pop_init_lb: -0.1
phase1_pop_init_ub: 0.1
phase2_pop_init: best+uniform_on_best_lb_ub
phase1_pop_size: 50
phase2_pop_size: 200
phase1_num_iterations: 10000
phase2_num_iterations: 40000
l2_reg_wd: 1e-3
adapter_k: 1024
test_interval: 10
save_path: logs/mnist/lenet/evo/2phase_full_then_uniform_binning/de/seed_42
wandb_entity: rasa_research
wandb_project: evonn
wandb_name: lenet-mnist-2phase-best+uniform_on_best_lb_ub-seed_42
disable_wandb: false
note: LeNet on MNIST with 2-phase training (full then uniform binning)
